[advisories]
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
vulnerability = "deny"
unmaintained = "warn"
yanked = "deny"
notice = "warn"
ignore = [
  "RUSTSEC-2020-0071"
]

[licenses]
unlicensed = "warn"
copyleft = "allow"
allow-osi-fsf-free = "both"
default = "warn"
